let numeros:number[] = [1,2,3,3,3,3,4]
let nombres:string[] = ['g','g','yy']
let coleccionnros:Array<number> = [1,2,3,2,2,21,2]
let coleccionnumbres:Array<string>  = ['g','g','yy']
let siono:boolean[] = [true,false,true]